sonata_admin:
    title: 'Sonata Admin'
    options:
        html5_validate:       true
        sort_admins:          false
        confirm_exit:         true
        use_select2:          true
        use_icheck:           true
        use_bootlint:         false
        use_stickyforms:      true
        form_type:            standard
        title_mode:           "single_text"
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    assets:
        extra_stylesheets:
            - /bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]