# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    listener.appellation:
        class: App\Listener\Wine\AppellationListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: doctrine.event_listener, event: onFlush,  method: onFlush }
            - { name: doctrine.event_listener, event: prePersist,  method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate,  method: preUpdate }

    listener.domain:
        class: App\Listener\Wine\DomainListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: doctrine.event_listener, event: onFlush,  method: onFlush }
            - { name: doctrine.event_listener, event: prePersist,  method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate,  method: preUpdate }

    listener.color:
        class: App\Listener\Wine\ColorListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: doctrine.event_listener, event: onFlush,  method: onFlush }
            - { name: doctrine.event_listener, event: prePersist,  method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate,  method: preUpdate }

    listener.capacity:
        class: App\Listener\Wine\CapacityListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: doctrine.event_listener, event: onFlush,  method: onFlush }
            - { name: doctrine.event_listener, event: prePersist,  method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate,  method: preUpdate }

    listener.region:
        class: App\Listener\Wine\RegionListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: doctrine.event_listener, event: onFlush,  method: onFlush }
            - { name: doctrine.event_listener, event: prePersist,  method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate,  method: preUpdate }

    listener.wine:
        class: App\Listener\Wine\WineListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: doctrine.event_listener, event: onFlush,  method: onFlush }
            - { name: doctrine.event_listener, event: prePersist,  method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate,  method: preUpdate }

    listener.bottle:
        class: App\Listener\Wine\BottleListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: doctrine.event_listener, event: onFlush,  method: onFlush }
            - { name: doctrine.event_listener, event: prePersist,  method: prePersist }
            - { name: doctrine.event_listener, event: preUpdate,  method: preUpdate }